### ISSUE TITLE
Error: unable to get latest build for orig/project-1

### ISSUE THREAD

**Issue by ozbillwang** [drone-plugins/drone-downstream#34]
Run well with `plugins/downstream` image for several months, suddenly it doesn't work with this error

    Error: unable to get latest build for orig/project-1

I found the image tags in hub.docker.com was updated 12 days ago. So is it related new commit recently in this repo?

My downstream pipeline:
```
 notify_downstream_repositories:
   image: plugins/downstream
   server: https://drone.example.io
   secrets: [ downstream_token ]
   fork: true
   repositories:
         - orig/project-1
```

**Comment by marcusramberg** [comment]
I'm also seeing this error. :( Would be nice if it had some more info about what actually failed.

**Comment by ozbillwang** [comment]
@marcusramberg 

Thanks for the confirmation.

I raised another issue #32, if the tag was not overrided with new commits, I can easily switch to old one. 

But currently not this case. All jobs with downstream plugins are failed. The whole CD processes is stopped.

**Comment by gboddin** [comment]
We're also facing the same issue

**Comment by gboddin** [comment]
To whom it may concerns, try removing the trailing slash from your `downstream_server`

**Comment by one000mph** [comment]
I am also facing this issue with the image `plugins/downstream`. I have experienced a (possibly-related) issue which prevents github deploy webhooks from triggering drone builds when the most recent build for a repo failed. 

Interestingly enough I was able to retrieve latest build using `drone-node` via CLI and I was able to successfully restart a downstream build by running `plugins/downstream` locally like so ```
docker run --rm -e PLUGIN_REPOSITORIES=me/repo -e PLUGIN_TOKEN=<token> -e PLUGIN_SERVER=https://drone.<me>.com -v $(pwd):$(pwd) -w $(pwd) plugins/downstream
Restarting build 36 for me/repo
```

This makes me suspect that the drone server is cacheing the downstream repo incorrectly. I don't want to clear my build history if I can help it, but if that's the only solution I will. Does anyone have thoughts or advice? Thanks!

**Comment by bradrydzewski** [comment]
> I was able to successfully restart a downstream build by running plugins/downstream locally

Since the plugin works when run locally (via `docker run`) it would typically tell me that something is configured incorrectly in your server environment. This could have something to do with the Yaml configuration file, secrets, host machine DNS, etc.

> This makes me suspect that the drone server is cacheing the downstream repo incorrectly

There is no caching in place, so I do not believe this could be a potential root cause.

> Does anyone have thoughts or advice? 

This is the line of code that returns the error message:

```
build, err := client.BuildLast(owner, name, branch)
if err != nil {
	if waiting {
		continue
	}
	return fmt.Errorf("Error: unable to get latest build for %s.\n", entry)
}
```

Unfortunately it looks like this plugin does not show the actual error message that is being returned from the http request. I therefore think the next step would be for someone to alter this plugin to print the error message, so that there is more visibility into what is going wrong. Without an error message, we are left speculating.

**Comment by one000mph** [comment]
@bradrydzewski thanks for the response. I also had the idea to alter the plugin to debug further, but so far I've had a difficult time successfully building a custom version of the downstream plugin due to environment issues. I'm getting this error `standard_init_linux.go:190: exec user process caused "exec format error"` both locally and when I use on my drone server. I will give it another shot tomorrow.

**Comment by bradrydzewski** [comment]
>  I'm getting this error standard_init_linux.go:190: exec user process caused "exec format error" both locally and when I use on my drone server. I will give it another shot tomorrow.

make sure you are building the binary for the target architecture (linux). Check out https://github.com/drone-plugins/drone-downstream#docker

**Comment by one000mph** [comment]
update: my issue was an authentication error due to a missing token. i'm finding that almost all of problems with drone can be traced back to missing/incorrect secrets. Some plugins use implicitly specified secrets, and some still seem to want them the old way (i.e. `param: $${SECRET}`). *sigh*

**Comment by quantonganh** [comment]
https://github.com/drone-plugins/drone-downstream/commit/59b879170b02c7d63e3133cf4cc2c2b50c91cd2a#diff-70e973989f81df39acd35aa417b206bc

You can use `linux-amd64` tag: https://hub.docker.com/layers/plugins/downstream/linux-amd64/images/sha256-ffc0cba21babec28fdb5f73e7841065a36ab09bf1e6d1e9cc666db7f379dfc17

and now the error is:

> time="2019-12-20T07:14:04Z" level=fatal msg="Error: unable to get latest build for owner/downstream: client error 404: {\"message\":\"sql: no rows in result set\"}\n.\n"

**Comment by quantonganh** [comment]
Please look at this code: https://github.com/drone-plugins/drone-downstream/blob/master/plugin.go#L202

If your downstream repo doesn't have a build for the default branch, you have to specify which branch you want to build:

```
steps:
- name: trigger  
  image: plugins/downstream:linux-amd64
  settings:
    server: https://drone.example.com
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
    fork: true
    repositories:
      - octocat/Hello-World@develop
```
